# Generated by Django 4.1.5 on 2023-09-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
