# Generated by Django 4.1.5 on 2023-09-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientprofile_gender_patientprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='bloodgroup',
            field=models.CharField(choices=[('OP', 'O +ve'), ('ON', 'O -ve'), ('AP', 'A +ve'), ('AN', 'A -ve'), ('BP', 'B +ve'), ('BN', 'B -ve'), ('ABP', 'AB +ve'), ('ABN', 'AB -ve')], default='OP', max_length=6),
        ),
    ]
