# Generated by Django 4.1.5 on 2023-09-21 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patientprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='birthdate',
            field=models.DateField(default=datetime.date(2023, 9, 22)),
        ),
    ]
