# Generated by Django 4.1.5 on 2023-09-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patientprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='weight',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='certificate',
            field=models.FileField(default='NULL', upload_to=''),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='speciality',
            field=models.TextField(default='MBBS'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='work_address',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
