# Generated by Django 4.1.5 on 2023-11-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_doctorprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='birthdate',
            field=models.DateField(default='16/04/2003'),
        ),
    ]
