# Generated by Django 4.1.5 on 2023-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_doctorprofile_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificate',
            field=models.FileField(upload_to='media/'),
        ),
    ]
