# Generated by Django 4.1.5 on 2023-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_doctorprofile_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificate',
            field=models.FileField(default='w.pdf', upload_to='certi'),
        ),
    ]
