# Generated by Django 4.1.5 on 2023-11-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='BMI',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='GenHlth',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='HeartDiseaseAttack',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='HighBP',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='HighChol',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='Stroke',
            field=models.IntegerField(default=-1),
        ),
    ]
