# Generated by Django 4.1.5 on 2023-11-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_doctorprofile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='DoctorGeneralAdvice',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
