# Generated by Django 4.1.5 on 2023-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_report_doctorgeneraladvice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='weight',
        ),
        migrations.AlterField(
            model_name='report',
            name='DoctorGeneralAdvice',
            field=models.TextField(default='abc'),
        ),
    ]
