# Generated by Django 4.1.5 on 2023-11-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_report_time_alter_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='CholestrolLevel',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='report',
            name='DiastolicBP',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='report',
            name='GlucoseLevel',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='report',
            name='Height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='report',
            name='PhysicalActivity',
            field=models.CharField(default='-1', max_length=60),
        ),
        migrations.AddField(
            model_name='report',
            name='Smoking',
            field=models.CharField(default='-1', max_length=60),
        ),
        migrations.AddField(
            model_name='report',
            name='SystolicBP',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='report',
            name='Weight',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='HeartDiseaseAttack',
            field=models.CharField(default='-1', max_length=60),
        ),
        migrations.AlterField(
            model_name='report',
            name='HighBP',
            field=models.CharField(default='-1', max_length=60),
        ),
        migrations.AlterField(
            model_name='report',
            name='HighChol',
            field=models.CharField(default='-1', max_length=60),
        ),
        migrations.AlterField(
            model_name='report',
            name='Stroke',
            field=models.CharField(default='-1', max_length=60),
        ),
    ]
