# Generated by Django 4.2.7 on 2023-11-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_report_cholestrollevel_report_diastolicbp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='birthdate',
            field=models.DateField(default='2003-04-16'),
        ),
    ]
